# Generated by Django 5.2 on 2026-06-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_amount_remove_order_price_and_more'),
        ('products', '0005_alter_product_subcategory_alter_sizeenabled_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'ordering': ['-product', 'price'],
            },
        ),
    ]
