# Generated by Django 5.2 on 2026-06-13 17:36
import datetime
from django.utils import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Дата/время заказа'),
            preserve_default=False,
        ),
    ]
