# Generated by Django 5.2 on 2026-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status_alter_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
