# Generated by Django 5.2 on 2026-06-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-order__created_at'], 'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказах'},
        ),
    ]
