# Generated by Django 5.2 on 2026-06-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_options_alter_orderproduct_options'),
        ('products', '0007_alter_sizeenabled_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizeenabled', verbose_name='Размер'),
        ),
    ]
