# Generated by Django 5.2 on 2026-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Подтверждён', 'Подтверждён'), ('Отменён', 'Отменён')], default='Активный', max_length=20, verbose_name='Статус'),
        ),
    ]
