# Generated by Django 5.2 on 2026-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeavailable',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер'),
        ),
    ]
