# Generated by Django 5.2 on 2026-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_sizeavailable_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Босоножки', 'Босоножки'), ('Ботинки', 'Ботинки'), ('Кроссовки', 'Кроссовки'), ('Сапоги', 'Сапоги'), ('Туфли', 'Туфли')], max_length=100, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='sizeenabled',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер'),
        ),
    ]
