# Generated by Django 5.2 on 2026-06-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_sizeenabled_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeenabled',
            options={'ordering': ['product', 'size_av']},
        ),
        migrations.RenameField(
            model_name='sizeenabled',
            old_name='size',
            new_name='size_av',
        ),
    ]
